[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_token_presale = "AmMwHG7vR4YhwQdPd4JK4QMtpbgjqXLfRxmMXqBFoUWV"

[programs.devnet]
solana_token_presale = "AmMwHG7vR4YhwQdPd4JK4QMtpbgjqXLfRxmMXqBFoUWV"

[programs.mainnet]
solana_token_presale = "AmMwHG7vR4YhwQdPd4JK4QMtpbgjqXLfRxmMXqBFoUWV"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "localnet"
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
